port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894

allow-lan: true
bind-address: "*"

find-process-mode: strict
mode: rule

geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
geo-auto-update: false
geo-update-interval: 24

log-level: silent
ipv6: true

external-controller: 0.0.0.0:9090
external-ui: /data/adb/box/clash/dashboard
external-ui-name: Meta
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

global-client-fingerprint: chrome
keep-alive-interval: 180
experimental:
hosts:

profile:
  store-selected: true
  store-fake-ip: false

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-detect-interface: true
  auto-route: true
  mtu: 9000

# sniffer:
#   enable: false
#   override-destination: false
#   sniff:
#     QUIC:
#     TLS:
#     HTTP:
#       ports: [80, 8080-8880]
#       override-destination: true
#   force-domain:
#     - +.v2ex.com
#   sniffing:
#     - tls
#     - http
#   port-whitelist:
#     - "80"
#     - "443"

dns:
  cache-algorithm: arc
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 119.29.29.29
    - https://8.8.8.8/dns-query
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    - https://1.1.1.1/dns-query
  enhanced-mode: redir-host
  use-hosts: true
  nameserver:
    - 119.29.29.29
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
  #   - 'tcp://1.1.1.1#ProxyGroupName' # 指定 DNS 过代理查询，ProxyGroupName 为策略组名或节点名，过代理配置优先于配置出口网卡，当找不到策略组或节点名则设置为出口网卡

  配置 fallback 使用条件
  fallback-filter:
    geoip: true # 配置是否使用 geoip
    geoip-code: CN # 当 nameserver 域名的 IP 查询 geoip 库为 CN 时，不使用 fallback 中的 DNS 查询结果
    配置强制 fallback，优先于 IP 判断，具体分类自行查看 geosite 库
    geosite:
      - gfw
  #   如果不匹配 ipcidr 则使用 nameservers 中的结果
  #   ipcidr:
  #     - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'

proxies:

proxy-groups:

rules:
